### ISSUE TITLE
Something backwards?

### ISSUE THREAD

**Issue by mikey-s** [masc4ii/ConfiguratorModelD#1]
I know nothing about code or programming, but as a Behringer Model D user, I've tried your configurator.

I could adjust the pitch bend down to where I wanted it, but only when it was set to "fixed". When set to "settable" it remained at 12.

Thanks. I love this thing, but am I reading it wrong, or is something backwards?

**Comment by masc4ii** [comment]
Japp, that seems to be an error by Behringer. The app does exactly what is written in the manual, but the manual or Model D firmware seems to be wrong.

**Comment by masc4ii** [comment]
Behringer updated the wrong manual and corrected the bug, so I could correct the software.
https://github.com/masc4ii/ConfiguratorModelD/commit/8607cdc8e661b6575d431704763516326b6dccfd
